-- MySQL Script generated by MySQL Workbench
-- Tue Jul  9 16:02:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` DEFAULT CHARACTER SET utf8 ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`Author` (
  `idAuthor` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `yearOfBirth` INT(4) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `biography` TEXT(2048) NULL,
  PRIMARY KEY (`idAuthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`Category` (
  `idCategory` INT(10) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`Format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`Format` (
  `idFormat` INT(10) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFormat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`Product` (
  `idProduct` INT(10) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `cover` VARCHAR(150) NOT NULL,
  `releaseDate` DATE NOT NULL,
  `Author_idAuthor` INT NOT NULL,
  `Category_idCategory` INT NOT NULL,
  `Format_idFormat` INT(10) NOT NULL,
  `price` FLOAT(6,2) NOT NULL,
  `available` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_Product_Author_idx` (`Author_idAuthor` ASC) VISIBLE,
  INDEX `fk_Product_Category1_idx` (`Category_idCategory` ASC) VISIBLE,
  INDEX `fk_Product_Format1_idx` (`Format_idFormat` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Author`
    FOREIGN KEY (`Author_idAuthor`)
    REFERENCES `bookstore`.`Author` (`idAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `bookstore`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Format1`
    FOREIGN KEY (`Format_idFormat`)
    REFERENCES `bookstore`.`Format` (`idFormat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`User` (
  `idUser` INT(10) NOT NULL AUTO_INCREMENT,
  `lastName` VARCHAR(50) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `hashPassword` VARCHAR(60) NOT NULL,
  `isAdministrator` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`PaymentMethod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`PaymentMethod` (
  `idPaymentMethod` INT(10) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(150) NULL,
  PRIMARY KEY (`idPaymentMethod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`Order` (
  `idOrder` INT(10) NOT NULL AUTO_INCREMENT,
  `User_idUser` INT(10) NOT NULL,
  `paymentMethod_idpaymentMethod` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `name` VARCHAR(101) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_Order_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Order_paymentMethod1_idx` (`paymentMethod_idpaymentMethod` ASC) VISIBLE,
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `bookstore`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_paymentMethod1`
    FOREIGN KEY (`paymentMethod_idpaymentMethod`)
    REFERENCES `bookstore`.`PaymentMethod` (`idPaymentMethod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`Cart` (
  `User_idUser` INT(10) NOT NULL,
  `date` DATETIME NOT NULL,
  `Product_idProduct` INT(10) NOT NULL,
  `qtde` INT(2) NOT NULL,
  INDEX `fk_Cart_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Cart_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  PRIMARY KEY (`User_idUser`, `Product_idProduct`),
  CONSTRAINT `fk_Cart_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `bookstore`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `bookstore`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`OrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`OrderItem` (
  `Order_idOrder` INT(10) NOT NULL,
  `Product_idProduct` INT(10) NOT NULL,
  `qtde` INT(2) NOT NULL,
  `price` FLOAT(6,2) NOT NULL,
  INDEX `fk_OrderItem_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  INDEX `fk_OrderItem_Order1_idx` (`Order_idOrder` ASC) VISIBLE,
  PRIMARY KEY (`Order_idOrder`, `Product_idProduct`),
  CONSTRAINT `fk_OrderItem_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `bookstore`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `bookstore`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
